name: CI

on:
  push:
  pull_request:

jobs:
  build-test-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test
  
      - name: Audit dependencies 
        run: npm audit --audit-level=high || true

    
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: secure-rest-api-node
          path: .
          format: HTML
          args: >
            -f JSON -f SARIF
            --out odc-report
            --data odc-data
            --failOnCVSS ${{ env.FAIL_ON_CVSS }}

          
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: odc-report

      - name: Print summary path
        run: |
          echo "HTML report: odc-report/dependency-check-report.html"
          echo "JSON report: odc-report/dependency-check-report.json"

